### ISSUE TITLE
5.12 Roadmap

### ISSUE THREAD

**Issue by Aqours** [Semibold/Weibo-Picture-Store#109]
- [x] 使用 TypeScript 类型提示
- [x] 微博相关的 API 全部使用 https，防止 ISP 劫持 cookie
- [x] 优化通知
- [x] 更新文档
- [x] 去除日志歧义命名
- [x] SVG宽高检测优化
- [x] 重试无伪造 Referer 的情况
- [x] 右键上传权限选项说明更改（实际上是影响 CORS）
- [x] 历史页面使用满屏宽度
- [x] 火狐扩展支持上传 blob 视频帧
